baseURL = 'https://russianbulbasaur.github.io/'
languageCode = 'en'
defaultContentLanguage = 'en'
title = 'Ankit'
theme = 'hugo-coder'
enableEmoji = true

[pagination]
  pagerSize = 20

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    codeFences = true
    lineNos    = false
    noClasses  = false
    style      = 'monokai'
    tabWidth   = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[params]
  author = 'Ankit'
  info = 'Perpetual learner with a running habit'
  location = 'Dharamshala, India'
  description = "Ankit's personal website"
  keywords = 'blog,developer,personal'
  avatarURL = 'avatar.png'
  favicon_32 = '/avatar.png'
  favicon_16 = '/avatar.png'
  touchicon = '/avatar.png'
  customCSS = ['css/custom.css']
  dateFormat = 'Jan 02, 2006'
  colorScheme = 'dark'
  hideColorSchemeToggle = false
  maxSeeAlsoItems = 5

[[params.social]]
  name = 'Github'
  icon = 'fa-brands fa-github fa-lg'
  weight = 1
  url = 'https://github.com/russianbulbasaur/'

[[params.social]]
  name = 'YouTube'
  icon = 'fa-brands fa-youtube fa-lg'
  weight = 2
  url = 'https://www.youtube.com/@russianbulbasaur'

[[params.social]]
  name = 'LinkedIn'
  icon = 'fa-brands fa-linkedin fa-lg'
  weight = 3
  url = 'https://www.linkedin.com/in/anki-t/'

[[params.social]]
  name = 'Strava'
  icon = 'fa-brands fa-strava fa-lg'
  weight = 4
  url = 'https://www.strava.com/athletes/ankitthakur'

[languages.en]
  languageName = 'English'

[[languages.en.menu.main]]
  name = 'Blog'
  weight = 1
  url = 'posts/'

[[languages.en.menu.main]]
  name = 'Walkthroughs'
  weight = 2
  url = 'walkthroughs/'

[[languages.en.menu.main]]
  name = 'Clixi Diaries'
  weight = 3
  url = 'clixidiaries/'
